from building import * 

# get current dir path

cwd = GetCurrentDir()

src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']


# init src and inc vars
# src = []
# inc = []

# add dwin basic include
# inc = inc + [cwd]
# inc = inc + [cwd + "/basic"]
# inc = inc + [cwd + "/widgets"]

# add dwin basic code
# src = src + Glob('./*.c')
# src = src + Glob('./basic/*.c')
# src = src + Glob('./widgets/*.c')

group = DefineGroup('dwin', src, depend = ['PKG_USING_DWIN'], CPPPATH = CPPPATH)

Return('group')
