from building import * 

cwd = GetCurrentDir()
src     = Glob('*.c')
# CPPPATH = [cwd + '/../inc']
inc = ['/../inc']

group = DefineGroup('dwin', src, depend = ['PKG_USING_DWIN'], CPPPATH = inc)

Return('group')
