from building import * 

cwd = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('Dwin', src, depend = ['PKG_USING_DWIN'], CPPPATH = CPPPATH)

Return('group')
